### ISSUE TITLE
Hud doesn't appear 

### ISSUE THREAD

**Issue by Mariioo23** [Yuvix25/ReHUD#1]
Hi, I installed Rehud yesterday and I followed the instructions but when I start raceroom the hud doesn't appear in the game window, collects and displays info but only on the desktop

**Comment by Yuvix25** [comment]
Hi, what do you mean by "displays info but only on the desktop"? Does it show up only when you minimize RaceRoom?

**Comment by Mariioo23** [comment]
Yes and I don't know why, many thanks for your concern.

**Comment by Yuvix25** [comment]
Sorry for the late response, forgot to hit "Comment".
Are you on single screen or multi screen? And if you're on multi, on which screen does it show up?
Also, could you attach a screenshot of how the HUD looks when you're in the desktop?

**Comment by Yuvix25** [comment]
I've done some testing, and it does indeed seem as if the overlay will not be displayed when using RaceRoom in fullscreen mode. I've also tried making it work with fullscreen, but unfortunately I don't think it is possible considering the framework I'm using to develop it. So in order to use ReHUD I'm afraid you'll have to put RaceRoom in borderless-windowed/windowed mode.

**Comment by Mariioo23** [comment]
Well, using the borderless windowed mode is better than nothing with such a well done hud, thank you very much for the help.

**Comment by Yuvix25** [comment]
Thanks for the feedback! I'll write back to you in this thread if I find a solution for fullscreen.
